using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Storage.Models;
using Storage.ViewModel;

namespace Storage.Data
{
    public class StorageContext : DbContext
    {
        public StorageContext (DbContextOptions<StorageContext> options)
            : base(options)
        {
        }

        public DbSet<Storage.Models.Product> Product { get; set; } = default!;

       // this code has been autogenerated, we dont need the view-model tables in db
       // public DbSet<Storage.ViewModel.ProductIndexViewModel> ProductIndexViewModel { get; set; } = default!;
    }
}
